#
#Thu Mar 12 12:14:15 PET 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized, --test-type, --no-sandbox, --ignore-certificate-errors, --window-size\=1920,1080], extensions\=[]}
